name: Publish Artifact
on:
  workflow_dispatch:
jobs:
  build:
    name: Build
    uses: ./.github/workflows/build-artifact.yml

  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    steps:
      - name: Version
        run: echo "Version builded ${{ needs.build.outputs.version }}"

      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: List files
        run: ls -R

      - name: Archive artifacts
        run: |
          zip -r "DynmapImageExport-Windows.zip" "DynmapImageExport(win)"
          zip -r "DynmapImageExport-Linux.zip" "DynmapImageExport(linux)"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            DynmapImageExport-Windows.zip
            DynmapImageExport-Linux.zip
